backend:
  name: git-gateway
  branch: main # Ensure this matches your repository's default branch

media_folder: "static/images/uploads" # Path to store uploaded images in the repository
public_folder: "/images/uploads" # URL path for uploaded images

collections:
  - name: "pages" # Collection for all pages
    label: "Pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: "Content", name: "content", widget: "markdown" }

      - label: "About Us"
        name: "aboutus"
        file: "aboutus.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: "Content", name: "content", widget: "markdown" }

      - label: "Anti-Wrinkle"
        name: "antiwrinkle"
        file: "antiwrinkle.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: "Content", name: "content", widget: "markdown" }

      - label: "Face Treatments"
        name: "facetreatments"
        file: "facetreatments.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: "Content", name: "content", widget: "markdown" }

      - label: "Hair Treatments"
        name: "hairtreatments"
        file: "hairtreatments.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: "Content", name: "content", widget: "markdown" }

      - label: "HydraFacial"
        name: "hydrafacial"
        file: "hydrafacial.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: "Content", name: "content", widget: "markdown" }

      - label: "Laser Hair"
        name: "laserhair"
        file: "laserhair.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: "Content", name: "content", widget: "markdown" }

      - label: "PRP Face"
        name: "prpface"
        file: "prpface.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: "Content", name: "content", widget: "markdown" }

      - label: "PRP Treatments"
        name: "prptreatments"
        file: "prptreatments.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: "Content", name: "content", widget: "markdown" }

      - label: "Results"
        name: "results"
        file: "results.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: "Content", name: "content", widget: "markdown" }

      - label: "RF Micro"
        name: "rfmicro"
        file: "rfmicro.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: "Content", name: "content", widget: "markdown" }

      - label: "Vitamin Therapy"
        name: "vitamin"
        file: "vitamin.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: "Content", name: "content", widget: "markdown" }

      - label: "Warts Removal"
        name: "warts"
        file: "warts.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: "Content", name: "content", widget: "markdown" }

